"use client";

import React, { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Minus, Plus, Shield, Target } from 'lucide-react';
import PublicHeader from '../components/PublicHeader';

// ─── Main Landing Page ────────────────────────────────────────────────────────
export default function Home() {
  const [openFaqIndices, setOpenFaqIndices] = useState([]);
  const faqRef = useRef(null);

  useEffect(() => {
    if (window.location.hash !== '#faq') return;

    window.requestAnimationFrame(() => {
      faqRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    });
  }, []);

  const toggleFaq = (index) => {
    setOpenFaqIndices((prev) =>
      prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index]
    );
  };

  const faqs = [
    {
      question: "What is VeritasAI?",
      answer: "VeritasAI is a leading AI content and misinformation detector designed to analyze text and determine if it was authored by humans or generated by artificial intelligence tools like ChatGPT, GPT-4, Claude, or Gemini."
    },
    {
      question: "How does AI detection work?",
      answer: "VeritasAI uses machine learning models trained on millions of pages of human-written and AI-generated text. It analyzes linguistic patterns, perplexity (sentence structure predictability), and burstiness (variation in sentence lengths) to determine authenticity."
    },
    {
      question: "Is VeritasAI's AI detector accurate?",
      answer: "Yes, VeritasAI operates at a 90% accuracy rate, minimizing false positives while reliably flagging AI-generated text."
    },
    {
      question: "Who is VeritasAI for?",
      answer: "It is built for educators verifying student submissions, publishers and editors maintaining content integrity, content creators, and businesses checking copy authenticity."
    },
    {
      question: "Does VeritasAI store my submitted text?",
      answer: "Signed-in scans are stored securely in your private history so you can revisit them. You can delete saved scans from the history drawer at any time."
    }
  ];

  return (
    <div className="min-h-screen bg-[#FDFBF7] text-[#1C1917] relative overflow-x-hidden flex flex-col font-sans">
      <div className="absolute top-[55%] left-1/2 -translate-x-1/2 -translate-y-1/2 w-[140%] h-[350px] bg-gradient-to-r from-transparent via-[#7B82FF]/10 to-transparent blur-[120px] pointer-events-none z-0"></div>
      <div className="absolute top-[55%] left-1/2 -translate-x-1/2 -translate-y-1/2 w-[80%] h-[150px] bg-[#7B82FF]/10 blur-[100px] pointer-events-none z-0"></div>

      <PublicHeader />

      <main className="flex-1 flex flex-col items-center pt-32 relative z-10 px-4">
        <div className="text-center max-w-4xl mx-auto flex flex-col gap-6">
          <h1 className="text-4xl sm:text-5xl lg:text-[60px] font-extrabold text-stone-900 tracking-tight leading-none">
            About <span className="text-[#7B82FF]">VeritasAI</span>
          </h1>
          <p className="text-stone-600 text-[17px] leading-relaxed max-w-[800px] mx-auto font-medium">
            At VeritasAI, we believe ensuring AI text authenticity should be simple. We're here to help you identify AI-generated content, improve source credibility, and connect with your audience on a deeper level.
          </p>
          <div className="mt-4 flex gap-4 justify-center">
            <Link href="/register" className="bg-[#1FA463] text-white font-bold py-3 px-8 rounded-full shadow-md hover:bg-[#178a52] transition">
              Get Started Now
            </Link>
          </div>
        </div>

        <div className="relative z-20 w-full flex flex-col items-center px-4 mt-16 mb-16">
          <div className="w-full max-w-[1050px] bg-white rounded-3xl p-6 shadow-[0_20px_50px_rgba(28,25,23,0.03)] border border-stone-200/40">
            <div className="flex flex-col md:flex-row divide-y md:divide-y-0 md:divide-x divide-stone-100 w-full">
              <div className="flex flex-col items-center md:items-start text-center md:text-left p-8 md:p-10 gap-4 flex-1">
                <div className="w-[56px] h-[56px] rounded-2xl bg-[#E8F8F5] flex items-center justify-center shadow-sm">
                  <Target size={28} className="text-[#10B981]" strokeWidth={2.5} />
                </div>
                <div>
                  <h3 className="text-4xl sm:text-[54px] font-black text-[#10B981] tracking-tight leading-none">90%</h3>
                  <p className="font-extrabold text-stone-900 text-xl mt-2">Detection Accuracy</p>
                </div>
                <p className="text-stone-500 text-[15px] leading-relaxed max-w-[280px]">
                  Industry-leading precision tuned specifically to minimize false positives.
                </p>
              </div>

              <div className="flex flex-col justify-center p-8 md:p-10 gap-6 flex-[1.5] border-t md:border-t-0 border-stone-100">
                <h4 className="text-[20px] font-bold text-stone-900 tracking-tight">How we achieve high accuracy</h4>
                <p className="text-stone-600 text-[15px] leading-relaxed font-medium">
                  VeritasAI is built on advanced linguistic analysis and machine learning models. By analyzing structural patterns, vocabulary consistency, and writing entropy, our detector accurately distinguishes between human creativity and AI-generated outputs.
                </p>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm font-semibold text-stone-700">
                  <div className="flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-[#10B981]"></span>
                    Multi-LLM recognition (GPT, Claude, Gemini)
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-[#10B981]"></span>
                    Sentence burstiness evaluation
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-[#10B981]"></span>
                    Minimizes false positives for human text
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-[#10B981]"></span>
                    Linguistic perplexity scoring
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-8 bg-white rounded-2xl sm:rounded-full py-3.5 px-4 sm:px-6 flex items-start sm:items-center gap-3 shadow-[0_10px_30px_rgba(28,25,23,0.03)] border border-stone-200/40">
            <div className="w-[30px] h-[30px] rounded-full bg-[#E5F5ED] flex items-center justify-center">
              <Shield size={16} className="text-[#10B981]" strokeWidth={3} />
            </div>
            <p className="text-[#4B5563] text-[15px] font-medium tracking-tight">
              Your scans stay private to your account, and you can delete saved history whenever you choose.
            </p>
          </div>
        </div>

        <section id="faq" ref={faqRef} className="relative z-20 w-full max-w-[900px] scroll-mt-24 mx-auto px-4 mt-12 mb-24">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-[40px] font-bold text-stone-900 tracking-tight">FAQs about VeritasAI</h2>
            <p className="text-stone-600 text-[16px] mt-3 font-medium">
              Everything you need to know about VeritasAI and our detection systems.
            </p>
          </div>

          <div className="flex flex-col gap-4">
            {faqs.map((faq, index) => {
              const isOpen = openFaqIndices.includes(index);
              return (
                <div 
                  key={index} 
                  className={`border bg-white rounded-2xl overflow-hidden transition-all duration-300 w-full ${
                    isOpen 
                      ? 'border-[#1FA463]/35 shadow-[0_10px_30px_rgba(31,164,99,0.025)]' 
                      : 'border-stone-200/80 shadow-[0_4px_20px_rgba(28,25,23,0.02)]'
                  } hover:border-[#1FA463] hover:shadow-[0_12px_40px_rgba(31,164,99,0.05)]`}
                >
                  <button
                    type="button"
                    onClick={() => toggleFaq(index)}
                    aria-expanded={isOpen}
                    className="w-full flex items-center justify-between p-6 text-left font-semibold text-base sm:text-lg text-stone-900 hover:text-[#1FA463] transition-colors select-none cursor-pointer"
                  >
                    <span>{faq.question}</span>
                    <span className="text-[#1FA463] shrink-0 ml-4 transition-transform duration-200">
                      {isOpen ? <Minus size={20} strokeWidth={2.5} /> : <Plus size={20} strokeWidth={2.5} />}
                    </span>
                  </button>
                  
                  <div 
                    className={`transition-all duration-300 ease-in-out overflow-hidden ${
                      isOpen ? 'max-h-[300px] border-t border-stone-100 opacity-100' : 'max-h-0 opacity-0'
                    }`}
                  >
                    <p className="p-6 text-stone-600 text-sm leading-relaxed font-medium bg-[#FCFAF7]">
                      {faq.answer}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </section>
      </main>
      

    </div>
  );
}
