"use client";

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { 
  HelpCircle, 
  MessageSquare, 
  ChevronDown, 
  ChevronUp, 
  Mail, 
  Send,
  AlertCircle
} from 'lucide-react';
import Sidebar from '../../components/Sidebar';
import { useToast } from '../../components/ToastProvider';
import safeLocalStorage from '../../utils/safeLocalStorage';

export default function SupportPage() {
  const router = useRouter();
  const { showToast } = useToast();
  
  const [activeTab, setActiveTab] = useState('faq');
  const [openFaqIndices, setOpenFaqIndices] = useState([]);
  const [isMounted, setIsMounted] = useState(false);

  // Form states
  const [formData, setFormData] = useState({ subject: '', message: '' });
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Sidebar info
  const [displayName, setDisplayName] = useState('Sulav Sharma');
  const subscriptionPlan = typeof window !== 'undefined' 
    ? safeLocalStorage.getItem('veritas_subscription_plan') || 'Free'
    : 'Free';

  useEffect(() => {
    setIsMounted(true);
    const savedName = safeLocalStorage.getItem('veritas_display_name');
    if (savedName) {
      setDisplayName(savedName);
    }
  }, []);

  const toggleFaq = (index) => {
    if (openFaqIndices.includes(index)) {
      setOpenFaqIndices(openFaqIndices.filter((i) => i !== index));
    } else {
      setOpenFaqIndices([...openFaqIndices, index]);
    }
  };

  const handleContactSubmit = (e) => {
    e.preventDefault();
    if (!formData.subject || !formData.message) {
      showToast('Please fill out all fields.', 'error');
      return;
    }
    
    setIsSubmitting(true);
    setTimeout(() => {
      setIsSubmitting(false);
      setFormData({ subject: '', message: '' });
      showToast('Your message has been sent to our support team!', 'success');
    }, 1500);
  };

  const faqs = [
    {
      question: "What is VeritasAI?",
      answer: "VeritasAI is a leading AI content and misinformation detector designed to analyze text and determine if it was authored by humans or generated by artificial intelligence tools like ChatGPT, GPT-4, Claude, or Gemini."
    },
    {
      question: "How does AI detection work?",
      answer: "VeritasAI uses machine learning models trained on millions of pages of human-written and AI-generated text. It analyzes linguistic patterns, perplexity, and burstiness to determine authenticity."
    },
    {
      question: "Is VeritasAI's AI detector accurate?",
      answer: "Yes, VeritasAI operates at a 90% accuracy rate, minimizing false positives while reliably flagging AI-generated text."
    },
    {
      question: "Does the text analyzer work for multiple languages?",
      answer: "Currently, our detection models are highly optimized for English. Support for Spanish, French, and German is available in Beta for Premium users."
    },
    {
      question: "How do I upgrade to Premium?",
      answer: "Navigate to the 'Plans & Pricing' tab in your dashboard sidebar to view available plans and upgrade via eSewa or Bank Transfer."
    }
  ];

  if (!isMounted) return <div className="min-h-screen bg-[#FDFBF7]" />;

  return (
    <div className="min-h-screen bg-[#FDFBF7] flex font-sans text-stone-800">
      
      <Sidebar 
        activeTab={activeTab === 'faq' ? 'faq' : 'support'} 
        displayName={displayName}
        subscriptionPlan={subscriptionPlan}
      />

      <main className="flex-1 p-4 sm:p-8 pt-14 md:pt-10 sm:pt-16 max-w-[1240px] mx-auto w-full flex flex-col justify-start transition-all duration-300">
        
        <div className="max-w-[800px] w-full mx-auto">
          {/* Support Header */}
          <div className="bg-gradient-to-br from-[#7755FF] to-[#4F33FF] rounded-[32px] p-8 md:p-10 text-white relative overflow-hidden shadow-lg mb-8">
            <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-white/10 blur-[80px] rounded-full translate-x-1/3 -translate-y-1/3 pointer-events-none"></div>
            <div className="relative z-10 flex flex-col items-center text-center">
              <h1 className="text-3xl md:text-4xl font-black tracking-tight mb-3">How can we help you?</h1>
              <p className="text-white/80 font-medium text-[15px] max-w-[500px]">
                Search our knowledge base or get in touch with our dedicated support team.
              </p>
            </div>
          </div>

          {/* Custom Tabs */}
          <div className="bg-white border border-stone-200/80 p-1.5 rounded-2xl flex items-center mb-8 shadow-sm">
            <button
              onClick={() => setActiveTab('faq')}
              className={`flex-1 py-3 px-6 rounded-xl font-bold text-[14px] transition-all flex items-center justify-center gap-2 ${
                activeTab === 'faq' 
                  ? 'bg-stone-900 text-white shadow-md' 
                  : 'text-stone-500 hover:text-stone-800 hover:bg-stone-50'
              }`}
            >
              <HelpCircle size={16} />
              Frequently Asked Questions
            </button>
            <button
              onClick={() => setActiveTab('contact')}
              className={`flex-1 py-3 px-6 rounded-xl font-bold text-[14px] transition-all flex items-center justify-center gap-2 ${
                activeTab === 'contact' 
                  ? 'bg-stone-900 text-white shadow-md' 
                  : 'text-stone-500 hover:text-stone-800 hover:bg-stone-50'
              }`}
            >
              <MessageSquare size={16} />
              Contact Support
            </button>
          </div>

          {/* Tab Content */}
          <div className="bg-white border border-stone-200/80 rounded-[24px] shadow-sm p-6 sm:p-8 animate-fade-in">
            
            {activeTab === 'faq' && (
              <div className="flex flex-col gap-6">
                <div>
                  <h2 className="text-2xl font-black text-stone-900 tracking-tight">Knowledge Base</h2>
                  <p className="text-stone-500 text-sm mt-1 font-medium">Quick answers to common questions about VeritasAI.</p>
                </div>
                
                <div className="flex flex-col gap-3">
                  {faqs.map((faq, index) => (
                    <div 
                      key={index} 
                      className={`border ${openFaqIndices.includes(index) ? 'border-[#7755FF]/30 bg-[#7755FF]/5' : 'border-stone-200 hover:border-stone-300 bg-white'} rounded-2xl overflow-hidden transition-all duration-300`}
                    >
                      <button
                        onClick={() => toggleFaq(index)}
                        className="w-full flex items-center justify-between p-4 sm:p-5 text-left focus:outline-none"
                      >
                        <span className={`font-bold text-[15px] pr-4 ${openFaqIndices.includes(index) ? 'text-[#7755FF]' : 'text-stone-800'}`}>
                          {faq.question}
                        </span>
                        <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 transition-colors ${openFaqIndices.includes(index) ? 'bg-[#7755FF]/20 text-[#7755FF]' : 'bg-stone-100 text-stone-500'}`}>
                          {openFaqIndices.includes(index) ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                        </div>
                      </button>
                      
                      <div 
                        className={`overflow-hidden transition-all duration-300 ease-in-out ${
                          openFaqIndices.includes(index) ? 'max-h-[500px] opacity-100' : 'max-h-0 opacity-0'
                        }`}
                      >
                        <div className="p-4 sm:p-5 pt-0 text-stone-600 text-[14px] leading-relaxed">
                          {faq.answer}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab === 'contact' && (
              <div className="flex flex-col gap-6">
                <div>
                  <h2 className="text-2xl font-black text-stone-900 tracking-tight">Send a Message</h2>
                  <p className="text-stone-500 text-sm mt-1 font-medium">Our team usually responds within 24 hours.</p>
                </div>

                <form onSubmit={handleContactSubmit} className="flex flex-col gap-5">
                  <div className="flex flex-col gap-2">
                    <label className="text-xs font-extrabold text-stone-500 uppercase tracking-wider pl-1">Issue Subject</label>
                    <div className="relative">
                      <div className="absolute left-4 top-1/2 -translate-y-1/2 text-stone-400">
                        <AlertCircle size={18} />
                      </div>
                      <input 
                        type="text" 
                        placeholder="E.g., Billing inquiry, False positive report..."
                        className="w-full pl-11 pr-4 py-3.5 bg-stone-50 border border-stone-200 rounded-xl focus:outline-none focus:border-[#7755FF] focus:ring-4 focus:ring-[#7755FF]/10 transition-all text-[15px] font-semibold text-stone-800 placeholder:text-stone-400 placeholder:font-medium"
                        value={formData.subject}
                        onChange={(e) => setFormData({...formData, subject: e.target.value})}
                      />
                    </div>
                  </div>

                  <div className="flex flex-col gap-2">
                    <label className="text-xs font-extrabold text-stone-500 uppercase tracking-wider pl-1">Details</label>
                    <textarea 
                      placeholder="Please provide as much context as possible..."
                      rows={5}
                      className="w-full p-4 bg-stone-50 border border-stone-200 rounded-xl focus:outline-none focus:border-[#7755FF] focus:ring-4 focus:ring-[#7755FF]/10 transition-all text-[15px] font-semibold text-stone-800 placeholder:text-stone-400 placeholder:font-medium resize-none"
                      value={formData.message}
                      onChange={(e) => setFormData({...formData, message: e.target.value})}
                    />
                  </div>

                  <button 
                    type="submit"
                    disabled={isSubmitting}
                    className="mt-2 w-full sm:w-auto self-end bg-gradient-to-r from-[#7755FF] to-[#4F33FF] hover:opacity-90 text-white px-8 py-3.5 rounded-xl font-bold text-[15px] transition-all shadow-md flex items-center justify-center gap-2 disabled:opacity-70 disabled:cursor-not-allowed active:scale-[0.98]"
                  >
                    {isSubmitting ? (
                      <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></span>
                    ) : (
                      <>
                        <Send size={18} />
                        Submit Request
                      </>
                    )}
                  </button>
                </form>
              </div>
            )}

          </div>
        </div>
      </main>
    </div>
  );
}
