"use client";

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { ShieldCheck, Target, Users, GraduationCap, Shield, Plus, Minus, Facebook, Linkedin, Twitter } from 'lucide-react';

export default function LandingPage() {
  const router = useRouter();
  const [openFaqIndices, setOpenFaqIndices] = useState([]);
  const [showHeader, setShowHeader] = useState(true);
  const [lastScrollY, setLastScrollY] = useState(0);

  useEffect(() => {
    const handleScroll = () => {
      const currentScrollY = window.scrollY;
      if (currentScrollY < 50) {
        setShowHeader(true);
      } else if (currentScrollY > lastScrollY) {
        setShowHeader(false);
      } else {
        setShowHeader(true);
      }
      setLastScrollY(currentScrollY);
    };

    window.addEventListener('scroll', handleScroll, { passive: true });
    return () => window.removeEventListener('scroll', handleScroll);
  }, [lastScrollY]);

  const toggleFaq = (index) => {
    setOpenFaqIndices((prev) =>
      prev.includes(index) ? prev.filter((i) => i !== index) : [...prev, index]
    );
  };

  const teamRef = React.useRef(null);
  const faqRef = React.useRef(null);

  const scrollToSection = (ref) => {
    ref.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const faqs = [
    {
      question: "What is VeritasAI?",
      answer: "VeritasAI is a leading AI content and misinformation detector designed to analyze text and determine if it was authored by humans or generated by artificial intelligence tools like ChatGPT, GPT-4, Claude, or Gemini."
    },
    {
      question: "How does AI detection work?",
      answer: "VeritasAI uses machine learning models trained on millions of pages of human-written and AI-generated text. It analyzes linguistic patterns, perplexity (sentence structure predictability), and burstiness (variation in sentence lengths) to determine authenticity."
    },
    {
      question: "Is VeritasAI's AI detector accurate?",
      answer: "Yes, VeritasAI operates at a 90% accuracy rate, minimizing false positives while reliably flagging AI-generated text."
    },
    {
      question: "Who is VeritasAI for?",
      answer: "It is built for educators verifying student submissions, publishers and editors maintaining content integrity, content creators, and businesses checking copy authenticity."
    },
    {
      question: "Does VeritasAI store my submitted text?",
      answer: "No. Privacy is our core priority. All submitted text is analyzed in real-time, and we never store or share your content."
    }
  ];

  return (
    <div className="min-h-screen bg-[#FDFBF7] text-[#1C1917] relative overflow-hidden flex flex-col font-sans">
      
      {/* Background Glow Effect - Sleek Cream Theme */}
      <div className="absolute top-[55%] left-1/2 -translate-x-1/2 -translate-y-1/2 w-[140%] h-[350px] bg-gradient-to-r from-transparent via-[#7B82FF]/10 to-transparent blur-[120px] pointer-events-none z-0"></div>
      <div className="absolute top-[55%] left-1/2 -translate-x-1/2 -translate-y-1/2 w-[80%] h-[150px] bg-[#7B82FF]/10 blur-[100px] pointer-events-none z-0"></div>

      {/* Header */}
      <header className={`fixed top-0 inset-x-0 z-50 flex items-center justify-between px-6 md:px-12 py-4 sm:py-5 bg-[#FDFBF7]/80 backdrop-blur-md border-b border-stone-200/40 shadow-[0_2px_20px_rgba(28,25,23,0.02)] transition-transform duration-300 ease-in-out ${showHeader ? 'translate-y-0' : '-translate-y-full'}`}>
        <div className="flex items-center gap-12">
          <div className="flex items-center gap-3">
            <div className="bg-gradient-to-br from-[#7755FF] to-[#4F33FF] p-[6px] rounded-lg shadow-lg">
              <ShieldCheck size={22} className="text-white" strokeWidth={2.5} />
            </div>
            <span className="font-bold text-[22px] tracking-tight text-stone-900">VeritasAI</span>
          </div>
          
          <div className="flex items-center gap-8">
            <button onClick={() => router.push('/subscription')} className="text-[15px] font-medium text-stone-600 hover:text-stone-900 transition-colors tracking-wide">
              Pricing
            </button>
            <button onClick={() => scrollToSection(teamRef)} className="text-[15px] font-medium text-stone-600 hover:text-stone-900 transition-colors tracking-wide">
              Team
            </button>
          </div>
        </div>
        
        <div className="flex items-center gap-8">
          <button onClick={() => router.push('/login')} className="text-[15px] font-medium text-stone-600 hover:text-stone-900 transition-colors tracking-wide">
            Login
          </button>
          <button onClick={() => router.push('/dashboard')} className="bg-[#7B82FF] hover:bg-[#6870fa] text-white text-[15px] font-bold py-2.5 px-6 rounded-full transition-all">
            Dashboard
          </button>
        </div>
      </header>

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col items-center pt-28 relative z-10 px-4">
        
        <div className="text-center max-w-4xl mx-auto flex flex-col gap-6">
          <h1 className="text-[60px] font-extrabold text-stone-900 tracking-tight">
            About VeritasAI
          </h1>
          
          <p className="text-stone-600 text-[17px] leading-relaxed max-w-[800px] mx-auto font-medium">
            At VeritasAI, we believe ensuring AI text authenticity should be simple. We're here to help you identify AI-generated content, improve source credibility, and connect with your audience on a deeper level.
          </p>
        </div>

      </main>
      
      {/* Stats Section & Privacy Pill */}
      <div className="relative z-20 w-full flex flex-col items-center px-4 mt-12 mb-16">
        {/* Stats Card */}
        <div className="w-full max-w-[1050px] bg-white rounded-3xl p-6 shadow-[0_20px_50px_rgba(28,25,23,0.03)] border border-stone-200/40">
          <div className="flex flex-col md:flex-row divide-y md:divide-y-0 md:divide-x divide-stone-100 w-full">
            
            {/* Left Side: 90% Accuracy Metric */}
            <div className="flex flex-col items-center md:items-start text-center md:text-left p-8 md:p-10 gap-4 flex-1">
              <div className="w-[56px] h-[56px] rounded-2xl bg-[#E8F8F5] flex items-center justify-center shadow-sm">
                <Target size={28} className="text-[#10B981]" strokeWidth={2.5} />
              </div>
              <div>
                <h3 className="text-[54px] font-black text-[#10B981] tracking-tight leading-none">90%</h3>
                <p className="font-extrabold text-stone-900 text-xl mt-2">Detection Accuracy</p>
              </div>
              <p className="text-stone-500 text-[15px] leading-relaxed max-w-[280px]">
                Industry-leading precision tuned specifically to minimize false positives.
              </p>
            </div>

            {/* Right Side: Detailed explanation */}
            <div className="flex flex-col justify-center p-8 md:p-10 gap-6 flex-[1.5] border-t md:border-t-0 md:border-l border-stone-100">
              <h4 className="text-[20px] font-bold text-stone-900 tracking-tight">How we achieve high accuracy</h4>
              <p className="text-stone-600 text-[15px] leading-relaxed font-medium">
                VeritasAI is built on advanced linguistic analysis and machine learning models. By analyzing structural patterns, vocabulary consistency, and writing entropy, our detector accurately distinguishes between human creativity and AI-generated outputs.
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm font-semibold text-stone-700">
                <div className="flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-[#10B981]"></span>
                  Multi-LLM recognition (GPT, Claude, Gemini)
                </div>
                <div className="flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-[#10B981]"></span>
                  Sentence burstiness evaluation
                </div>
                <div className="flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-[#10B981]"></span>
                  Minimizes false positives for human text
                </div>
                <div className="flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-[#10B981]"></span>
                  Linguistic perplexity scoring
                </div>
              </div>
            </div>

          </div>
        </div>

        {/* Privacy Pill */}
        <div className="mt-8 bg-white rounded-full py-3.5 px-6 flex items-center gap-3 shadow-[0_10px_30px_rgba(28,25,23,0.03)] border border-stone-200/40">
          <div className="w-[30px] h-[30px] rounded-full bg-[#E5F5ED] flex items-center justify-center">
            <Shield size={16} className="text-[#10B981]" strokeWidth={3} />
          </div>
          <p className="text-[#4B5563] text-[15px] font-medium tracking-tight">
            Your privacy is our priority. We <span className="text-[#10B981] font-bold">never</span> store your content.
          </p>
        </div>
      </div>



      {/* FAQ Section */}
      <section id="faq" ref={faqRef} className="relative z-20 w-full max-w-[900px] mx-auto px-4 mt-20 mb-24">
        <div className="text-center mb-12">
          <h2 className="text-[40px] font-bold text-stone-900 tracking-tight">FAQs about VeritasAI</h2>
          <p className="text-stone-600 text-[16px] mt-3 font-medium">
            Everything you need to know about VeritasAI and our detection systems.
          </p>
        </div>

        <div className="flex flex-col gap-4">
          {faqs.map((faq, index) => {
            const isOpen = openFaqIndices.includes(index);
            return (
              <div 
                key={index} 
                className={`border bg-white rounded-2xl overflow-hidden transition-all duration-300 w-full ${
                  isOpen 
                    ? 'border-[#1FA463]/35 shadow-[0_10px_30px_rgba(31,164,99,0.025)]' 
                    : 'border-stone-200/80 shadow-[0_4px_20px_rgba(28,25,23,0.02)]'
                } hover:border-[#1FA463] hover:shadow-[0_12px_40px_rgba(31,164,99,0.05)]`}
              >
                <button
                  type="button"
                  onClick={() => toggleFaq(index)}
                  className="w-full flex items-center justify-between p-6 text-left font-semibold text-base sm:text-lg text-stone-900 hover:text-[#1FA463] transition-colors select-none"
                >
                  <span>{faq.question}</span>
                  <span className="text-[#1FA463] shrink-0 ml-4 transition-transform duration-200">
                    {isOpen ? <Minus size={20} strokeWidth={2.5} /> : <Plus size={20} strokeWidth={2.5} />}
                  </span>
                </button>
                
                <div 
                  className={`transition-all duration-300 ease-in-out overflow-hidden ${
                    isOpen ? 'max-h-[300px] border-t border-stone-100 opacity-100' : 'max-h-0 opacity-0'
                  }`}
                >
                  <p className="p-6 text-stone-600 text-sm leading-relaxed font-medium bg-[#FCFAF7]">
                    {faq.answer}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </section>
      
      {/* Footer / Emerging Bottom Container */}
      <footer className="w-full flex justify-center relative z-10 mt-12">
        <div className="w-full max-w-[1200px] bg-white border-t border-x border-stone-200/60 rounded-t-[32px] shadow-[0_-15px_40px_rgba(28,25,23,0.03)] relative px-8 sm:px-12 pt-16 pb-12">
          {/* Cyan/Blue glow border on top */}
          <div className="absolute top-0 inset-x-0 h-px bg-gradient-to-r from-transparent via-[#7B82FF]/20 to-transparent"></div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-6 gap-8">
            {/* Column 1: Brand Info */}
            <div className="lg:col-span-2 flex flex-col gap-4">
              <div className="flex items-center gap-3">
                <div className="bg-gradient-to-br from-[#7755FF] to-[#4F33FF] p-[6px] rounded-lg shadow-lg">
                  <ShieldCheck size={20} className="text-white" strokeWidth={2.5} />
                </div>
                <span className="font-bold text-xl tracking-tight text-stone-900">VeritasAI</span>
              </div>
              <p className="text-stone-500 text-xs leading-relaxed max-w-[240px]">
                Ensuring AI text authenticity should be simple. We help preserve what is human.
              </p>
              <div className="flex items-center gap-3 mt-2 text-stone-400">
                <a href="#" className="hover:text-stone-900 transition-colors"><Facebook size={16} /></a>
                <a href="#" className="hover:text-stone-900 transition-colors"><Linkedin size={16} /></a>
                <a href="#" className="hover:text-[#1FA463] transition-colors"><Twitter size={16} /></a>
              </div>
              <div className="text-[11px] text-stone-400 font-medium mt-1">
                © 2023 - 2026 VeritasAI. All rights reserved.
              </div>
            </div>

            {/* Column 2: Products */}
            <div className="flex flex-col gap-3">
              <h4 className="text-stone-900 font-bold text-sm tracking-wide">Products</h4>
              <ul className="flex flex-col gap-2.5 text-xs font-medium text-stone-500">
                <li><a href="#" className="hover:text-stone-900 transition-colors">AI Detector</a></li>
                <li><a href="#" className="hover:text-stone-900 transition-colors">Misinformation Signals</a></li>
                <li><a href="#" className="hover:text-stone-900 transition-colors">Plagiarism Checker</a></li>
              </ul>
            </div>

            {/* Column 3: Resources */}
            <div className="flex flex-col gap-3">
              <h4 className="text-stone-900 font-bold text-sm tracking-wide">Resources</h4>
              <ul className="flex flex-col gap-2.5 text-xs font-medium text-stone-500">
                <li><button onClick={() => router.push('/subscription')} className="hover:text-stone-900 transition-colors text-left">Pricing</button></li>
                <li><a href="#" className="hover:text-stone-900 transition-colors">API Documentation</a></li>
                <li><a href="#" className="hover:text-stone-900 transition-colors">Educators Guide</a></li>
              </ul>
            </div>

            {/* Column 4: Company */}
            <div className="flex flex-col gap-3">
              <h4 className="text-stone-900 font-bold text-sm tracking-wide">Company</h4>
              <ul className="flex flex-col gap-2.5 text-xs font-medium text-stone-500">
                <li><a href="#" className="hover:text-stone-900 transition-colors">About us</a></li>
                <li><button onClick={() => scrollToSection(teamRef)} className="hover:text-stone-900 transition-colors text-left">Team</button></li>
                <li><a href="#" className="hover:text-stone-900 transition-colors">Blog</a></li>
              </ul>
            </div>

            {/* Column 5: Support */}
            <div className="flex flex-col gap-3">
              <h4 className="text-stone-900 font-bold text-sm tracking-wide">Help</h4>
              <ul className="flex flex-col gap-2.5 text-xs font-medium text-stone-500">
                <li><button onClick={() => scrollToSection(faqRef)} className="hover:text-stone-900 transition-colors text-left">FAQ</button></li>
                <li><a href="#" className="hover:text-stone-900 transition-colors">Privacy Policy</a></li>
                <li><a href="#" className="hover:text-stone-900 transition-colors">Terms of Use</a></li>
              </ul>
            </div>
          </div>

        </div>
      </footer>
      
    </div>
  );
}
